version: '3.8'

services:
    api:
        build:
            context: .
        container_name: fintech_api
        ports:
            - "3000:3000"
        env_file:
            - .env
        depends_on:
            - postgres
        networks:
            - fintech-network

    postgres:
        image: postgres:15-alpine
        container_name: fintech_postgres
        environment:
            POSTGRES_USER: ${DB_USERNAME:-postgres}
            POSTGRES_PASSWORD: ${DB_PASSWORD:-admin}
            POSTGRES_DB: ${DB_DATABASE:-fintech_db}
        volumes:
            - postgres-data:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        networks:
            - fintech-network
            
networks:
    fintech-network:
        name: fintech_network
        driver: bridge

volumes:
  postgres-data: